server:
  port: 9999

spring:
  redis:
    host: redis-server

  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysql-server:3306/kl-test?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl